#!/usr/bin/clitoris  ## -*- shell-script -*-

$ cat "${srcdir}/utf8-terms.txt" | glep2 --show-patterns -f "${srcdir}/stops.alrt"
als	1	<stdin>
are	1	<stdin>
at	2	<stdin>
be	1	<stdin>
dem	1	<stdin>
den	2	<stdin>
der	1	<stdin>
die	1	<stdin>
e	3	<stdin>
er	3	<stdin>
es	1	<stdin>
he	3	<stdin>
him	2	<stdin>
ich	4	<stdin>
im	1	<stdin>
in	2	<stdin>
kan	1	<stdin>
la	1	<stdin>
li	1	<stdin>
man	1	<stdin>
mit	2	<stdin>
n	2	<stdin>
ne	1	<stdin>
ob	1	<stdin>
on	1	<stdin>
s	2	<stdin>
sta	1	<stdin>
t	1	<stdin>
vil	1	<stdin>
was	1	<stdin>
werden	1	<stdin>
wil	2	<stdin>
а	11	<stdin>
бы	1	<stdin>
в	4	<stdin>
во	1	<stdin>
да	1	<stdin>
до	1	<stdin>
здесь	1	<stdin>
мы	1	<stdin>
не	5	<stdin>
но	2	<stdin>
о	21	<stdin>
он	2	<stdin>
по	1	<stdin>
с	10	<stdin>
со	1	<stdin>
там	1	<stdin>
то	2	<stdin>
ты	2	<stdin>
у	9	<stdin>
$
