#!/usr/bin/clitoris  ## -*- shell-script -*-

$ terms -l -n 2 "${srcdir}/1206796.txt"
21.12.2000 15:21
15:21 vectron
vectron aktien
aktien verkaufen
verkaufen für
für die
die aktien
aktien der
der vectron
vectron AG
AG gibt
gibt es
es von
von den
den analysten
analysten der
der bankgesellschaft
bankgesellschaft berlin
berlin eine
eine verkaufsempfehlung
verkaufsempfehlung der
der bisherige
bisherige finanzvorstand
finanzvorstand christoph
christoph haarbeck
haarbeck werde
werde sein
sein amt
amt zum
zum jahresende
jahresende niederlegen
niederlegen das
das amt
amt werde
werde nunmehr
nunmehr vom
vom bisherigen
bisherigen vorstandsmitglied
vorstandsmitglied olaf
olaf arlinghaus
arlinghaus bisher
bisher vorstand
vorstand organisation
organisation und
und unternehmensentwicklung
unternehmensentwicklung übernommen
übernommen die
die analysten
analysten vermuten
vermuten daß
daß damit
damit die
die konsequenzen
konsequenzen gezogen
gezogen werden
werden aus
aus den
den fehlern
fehlern im
im rechnungswesen
rechnungswesen und
und im
im controlling
controlling sowie
sowie aus
aus der
der nicht
nicht zufriedenstellenden
zufriedenstellenden berichterstattung
berichterstattung im
im jahr
jahr 2000
2000 obwohl
obwohl der
der wechsel
wechsel im
im vorstand
vorstand zur
zur hoffnung
hoffnung anlass
anlass geben
geben könnte
könnte dass
dass wieder
wieder mehr
mehr solidität
solidität in
in die
die finanzplanung
finanzplanung des
des unternehmens
unternehmens einzug
einzug hält
hält bleiben
bleiben sie
sie dabei
dabei dass
dass sie
sie die
die empfehlung
empfehlung erst
erst wieder
wieder hochstufen
hochstufen werden
werden wenn
wenn ihnen
ihnen eine
eine überzeugende
überzeugende neue
neue planung
planung vorliege
vorliege mit
mit der
der vorlage
vorlage neuer
neuer planzahlen
planzahlen rechnen
rechnen sie
sie jedoch
jedoch erst
erst ende
ende januar
januar 2001
2001 bis
bis dahin
dahin sehen
sehen die
die analysten
analysten keinen
keinen anpassungsbedarf
anpassungsbedarf für
für ihre
ihre bisherige
bisherige empfehlung

$

