#!/usr/bin/clitoris  ## -*- shell-script -*-

$ terms --ngram=3 "${srcdir}/1206796.txt"
21.12.2000 15:21 Vectron
15:21 Vectron Aktien
Vectron Aktien verkaufen
Aktien verkaufen Für
verkaufen Für die
Für die Aktien
die Aktien der
Aktien der Vectron
der Vectron AG
Vectron AG gibt
AG gibt es
gibt es von
es von den
von den Analysten
den Analysten der
Analysten der Bankgesellschaft
der Bankgesellschaft Berlin
Bankgesellschaft Berlin eine
Berlin eine Verkaufsempfehlung
eine Verkaufsempfehlung Der
Verkaufsempfehlung Der bisherige
Der bisherige Finanzvorstand
bisherige Finanzvorstand Christoph
Finanzvorstand Christoph Haarbeck
Christoph Haarbeck werde
Haarbeck werde sein
werde sein Amt
sein Amt zum
Amt zum Jahresende
zum Jahresende niederlegen
Jahresende niederlegen Das
niederlegen Das Amt
Das Amt werde
Amt werde nunmehr
werde nunmehr vom
nunmehr vom bisherigen
vom bisherigen Vorstandsmitglied
bisherigen Vorstandsmitglied Olaf
Vorstandsmitglied Olaf Arlinghaus
Olaf Arlinghaus bisher
Arlinghaus bisher Vorstand
bisher Vorstand Organisation
Vorstand Organisation und
Organisation und Unternehmensentwicklung
und Unternehmensentwicklung übernommen
Unternehmensentwicklung übernommen Die
übernommen Die Analysten
Die Analysten vermuten
Analysten vermuten daß
vermuten daß damit
daß damit die
damit die Konsequenzen
die Konsequenzen gezogen
Konsequenzen gezogen werden
gezogen werden aus
werden aus den
aus den Fehlern
den Fehlern im
Fehlern im Rechnungswesen
im Rechnungswesen und
Rechnungswesen und im
und im Controlling
im Controlling sowie
Controlling sowie aus
sowie aus der
aus der nicht
der nicht zufriedenstellenden
nicht zufriedenstellenden Berichterstattung
zufriedenstellenden Berichterstattung im
Berichterstattung im Jahr
im Jahr 2000
Jahr 2000 Obwohl
2000 Obwohl der
Obwohl der Wechsel
der Wechsel im
Wechsel im Vorstand
im Vorstand zur
Vorstand zur Hoffnung
zur Hoffnung Anlass
Hoffnung Anlass geben
Anlass geben könnte
geben könnte dass
könnte dass wieder
dass wieder mehr
wieder mehr Solidität
mehr Solidität in
Solidität in die
in die Finanzplanung
die Finanzplanung des
Finanzplanung des Unternehmens
des Unternehmens Einzug
Unternehmens Einzug hält
Einzug hält bleiben
hält bleiben sie
bleiben sie dabei
sie dabei dass
dabei dass sie
dass sie die
sie die Empfehlung
die Empfehlung erst
Empfehlung erst wieder
erst wieder hochstufen
wieder hochstufen werden
hochstufen werden wenn
werden wenn ihnen
wenn ihnen eine
ihnen eine überzeugende
eine überzeugende neue
überzeugende neue Planung
neue Planung vorliege
Planung vorliege Mit
vorliege Mit der
Mit der Vorlage
der Vorlage neuer
Vorlage neuer Planzahlen
neuer Planzahlen rechnen
Planzahlen rechnen sie
rechnen sie jedoch
sie jedoch erst
jedoch erst Ende
erst Ende Januar
Ende Januar 2001
Januar 2001 Bis
2001 Bis dahin
Bis dahin sehen
dahin sehen die
sehen die Analysten
die Analysten keinen
Analysten keinen Anpassungsbedarf
keinen Anpassungsbedarf für
Anpassungsbedarf für ihre
für ihre bisherige
ihre bisherige Empfehlung

$

