#!/usr/bin/clitoris ## -*- shell-script -*-

$ unwrap "${srcdir}/unwrap_test_02.txt"
/data/data-source/xetra-newsboard/download/1998/1998-10-12T05:37:15-Xetra_Trading_2_-REPORT_SELEKTION_SELECTION-news=15623&venue=1.html.xz
DIE AUSWAHL DER REPORTS WURDEN AUS DER SIMULATION UEBERNOMMEN. BITTE PRUEFEN SIE HEUTE IHRE REPORTAUSWAHL.   

REPORT SELECTIONS WERE TAKEN FROM SIMULATION. PLEASE CHECK YOUR REPORT REQUEST TODAY.   

MARKET SUPERVISION XETRA   

+69 - 21 01 - 14 00
$
